### ISSUE TITLE
Saturday Crosswords are Bigger

### ISSUE THREAD

**Issue by jidicula** [idoneam/minicrossword-bot#1]
Saturday crosswords should not be counted in the average with other daily crosswords and should instead be counted in their own category.

**Comment by mjip** [comment]
I'll work on this tonight. Do the crosswords use UTC time or something else altogether?

**Comment by Yuyu-Ren** [comment]
~~According to [the NYTimes help](https://help.nytimes.com/hc/en-us/articles/115014755667-New-York-Times-Crossword) their daily puzzles follow the current rule: 
![image](https://user-images.githubusercontent.com/8889046/43041296-2e74f9dc-8d19-11e8-9f1f-662ccdf9bb24.png) I'll try and confirm this to see if it also applies to the mini-crossword as it's not explicitly listed.~~
On second thought, It's currently 9:33PM ET and the new mini-crossword has been out since 4 hours ago. :thinking:
